### ISSUE TITLE
highlight color and occurrence color are alike

### ISSUE THREAD

**Issue by mcrajah** [JarvisPrestidge/VSCode-Material-Theme#1]
When I highlight a word (material dark), the color of occurrence is the same, this makes it difficult to tell them apart. Line 6 is the actual highlight and the rest are occurrences. I tried to look for the theme file to tweak the settings, but I was unable to find it in the user folder or the installation folder.
![capture](https://cloud.githubusercontent.com/assets/11020250/20851389/04e1c320-b895-11e6-811e-553c06dc7e43.JPG)

**Comment by JarvisPrestidge** [comment]
I'm starting to realized the initial port was a bit of a hack job that I missed alot of things. I intend to do some work this weekend to fix this and a couple of other differences between the original. I'll update once I push a commit to fix this. Thanks for the issue, sorry about the delay in response.

**Comment by mcrajah** [comment]
No worries, the theme is the best so far, a few rough edges can be
smoothened out over time.

**Comment by equinusocio** [comment]
@mcrajah I suggest you to try the original Material Theme for VSC
https://github.com/equinusocio/vsc-material-theme

**Comment by JarvisPrestidge** [comment]
@equinusocio  I approve this message!
