### ISSUE TITLE
Syntax Highlight doesn't match the original one

### ISSUE THREAD

**Issue by equinusocio** [JarvisPrestidge/VSCode-Material-Theme#2]
The syntax highlight color doesn't match the original ones. Color are completely different. 

PS: Please remove the the Material Theme ST repository.

**Comment by JarvisPrestidge** [comment]
Sure thing, I can remove that. I do intend to change this theme a fair bit to bring it more inline with the original.

Just so you know, this theme was intended to be a one-for-one port of yours, but with a single twist. The background chrome color of VSCode and it's sidebar can't be customized like Sublime's can, it's instead limited to a "light" and "dark" fixed color. I've only changed your theme's background to match these colors for the same clean look your original offered. I realize it looks quite different from the original material theme and I agree it shouldn't be on the official port list etc. But for this reason it will always different to some extent.

**Comment by equinusocio** [comment]
At the moment only the syntax and the comments/gutter color is different.
