### ISSUE TITLE
Original Material Theme porting

### ISSUE THREAD

**Issue by equinusocio** [JarvisPrestidge/VSCode-Material-Theme#3]
Hi, i will make the original Material Theme for vsc after the february update that add UI api. Official repo https://github.com/equinusocio/vsc-material-theme

**Comment by equinusocio** [comment]
@JarvisPrestidge I just released the beta version of Material Theme, i suggest you to remove this extension or write that the original version is online at https://github.com/equinusocio/vsc-material-theme

**Comment by JarvisPrestidge** [comment]
I'll be removing this theme over the weekend, thanks for making an official port :+1:
