### ISSUE TITLE
What file icon theme are you using?

### ISSUE THREAD

**Issue by ghost** [JarvisPrestidge/VSCode-Material-Theme#5]
Love the color scheme, was just wondering what file icon theme you're using in the screenshots?

**Comment by ghost** [comment]
nevermind, found it!

**Comment by lemonlatte** [comment]
@automaticlightyears May I ask what the theme name is? I still can not find it. :(

**Comment by JarvisPrestidge** [comment]
Thanks, I'm using the "Material Icon Theme".  I really advise you to start
using the real material theme that's being maintained by the original
creator. I don't have the link at hand but give it a search. Cheers.

**Comment by lemonlatte** [comment]
OK. Thanks a lot.

**Comment by yuqiao20** [comment]
@JarvisPrestidge May I ask the font name in the screenshots? Thanks a lot! :)
