### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lobosan** [JarvisPrestidge/VSCode-Material-Theme#6]
Hi, I just added the extension and uninstalled all my other extension and I even reinstall visual studio code completely to see if something was interfering but I'm not able to see the colors and icons shown in the example image.

I'm running the latest version of vscode on windows 10

**Comment by lobosan** [comment]
Sorry my bad, I didn't know that after installing I had to select the theme from preferences. Thanks for your beautiful theme ;)

**Comment by JarvisPrestidge** [comment]
Hi, I'd really recommend using the original creators version. That's what
i'm using now :D

https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme

He decided to port his own theme to VSCode and I believe he'll be keeping
it up-to-date too.

Cheers
